## IVT Orchestration

In [1]:
import xarray as xr
import numpy as np
from dask.distributed import Client
from dask import delayed
from tqdm import tqdm
from pathlib import Path

from config import era5_fp, ar_params, ard_fp

Let's verify the configuration. The "window" parameter will determine the number of days before and after a given DOY to compute IVT percentiles. For example, a value of 60 would create a fourth month window (60 days before a DOY and 60 days after).

In [2]:
ar_params["window"]

75

The way that this is configured is a little confusing to me, because the actual window is 2x this amount, half the days occuring before, and half the days occuring after, some targey date. For my testing I am going to create a `window_days` variable to represent how long the actual window of time is.

In [3]:
window_days = ar_params["window"] * 2
window_days

150

The quantile to compute, which must be between 0 and 1 inclusive. To be explicit: For some vector V, the q-th quantile of V is the value q of the way from the minimum to the maximum in a sorted copy of V. The default "percentile" is 85, so the q-th quantile in this case is the value estimated at 0.85 of the way between the minimum and maximum values. Note that in the NumPy implementation, the `quantile` and `percentile` functions are equivalent.

In [4]:
quantile = ar_params["ivt_percentile"] / 100

test_arr = np.array(range(101))

qth_quantile = np.quantile(test_arr, q=quantile)
qth_percentile = np.percentile(test_arr, q=ar_params["ivt_percentile"])

assert qth_percentile == qth_quantile == 85

In [5]:
# create dask client
client = Client()
client

<Client: 'tcp://127.0.0.1:36373' processes=8 threads=32, memory=251.72 GiB>

In [6]:
def magnitude(a, b):
    """
    compute IVT magnitude (output kg m**2/s**2) from eastward and northward components
    reference: https://www.eol.ucar.edu/content/wind-direction-quick-reference
    """
    func = lambda x, y: np.sqrt(x**2 + y**2)
    return xr.apply_ufunc(func, a, b, dask='parallelized')


def direction(a, b):
    """
    compute geographic IVT direction (degrees with respect to true north (0=north,90=east,180=south,270=west) that the wind is coming FROM)
    from eastward and northward components
    reference: https://www.eol.ucar.edu/content/wind-direction-quick-reference
    """
    func = lambda x, y: 270 - ((180 / np.pi) * np.arctan2(x, y))
    return xr.apply_ufunc(func, a, b, dask='parallelized')


In [7]:
# CP note: I've renamed this function to be more consistent about quantile vs. percentile to reduce my confusion
def compute_seasonal_quantile(da, window, target_quantile):
    """
    Compute a single quantile value for IVT magnitude over rolling time window.
    Recall that the input data 6-hr frequency, so there are 4 timesteps per day.
    This means that the window size (unit days) has to be multiplied by a factor of 4.
    These quantiles are for single period of time (e.g. 5 months) for a given year.
    """
    rolling_window = da.rolling(time=window * 4, center=True)
    qth_quantile = rolling_window.reduce(np.quantile, q=target_quantile)
    return qth_quantile

I want to test my understanding of how the rolling window arguments are interacting with the time dimension of the datacube.
I'll do this by comparing maximum values over a ten day slice centered on a certain date.

In [8]:
test_window_center_date = "2020-12-15T00:00:00"
test_window_days = 10

In [9]:
ds = xr.open_dataset(era5_fp)
# add DOY coords to input dataset
dsc = ds.assign_coords(doy=ds.time.dt.dayofyear)
dsc["ivt_mag"] = magnitude(dsc["p71.162"], dsc["p72.162"]).astype(int)
da = dsc["ivt_mag"]
# compare maximum values over a known ten day slice
tslice = da.sel(time=slice("2020-12-10T00:00:00", "2020-12-20T00:00:00")).max(axis=0)
ds.close()
tslice.data

array([[203, 211, 224, ..., 100, 101, 102],
       [235, 248, 267, ...,  96,  98,  99],
       [285, 294, 299, ...,  97,  97,  97],
       ...,
       [473, 495, 503, ..., 591, 569, 546],
       [481, 487, 493, ..., 614, 591, 567],
       [501, 506, 512, ..., 637, 615, 587]])

In [10]:
ds = xr.open_dataset(era5_fp)    
# add DOY coords to input dataset
dsc = ds.assign_coords(doy=ds.time.dt.dayofyear)
dsc["ivt_mag"] = magnitude(dsc["p71.162"], dsc["p72.162"]).astype(int)
da = dsc["ivt_mag"]
rolling_window_max = da.rolling(time=test_window_days * 4, center=True).max()
ds.close()
rolling_window_max.sel(time=test_window_center_date).data

array([[203., 211., 224., ..., 100., 101., 102.],
       [235., 248., 267., ...,  96.,  98.,  99.],
       [285., 294., 299., ...,  97.,  97.,  97.],
       ...,
       [473., 495., 503., ..., 591., 569., 546.],
       [481., 487., 493., ..., 614., 591., 567.],
       [501., 506., 512., ..., 637., 615., 587.]])

In [11]:
assert np.all(tslice.data == rolling_window_max.sel(time=test_window_center_date).data)

OK, so I'm confident that we can compute quantiles (or any statistic) over a rolling window using the actual window size in days, multiplied by 4 to account for the six-hour time frequency of the input dataset (four time steps per day).

In [12]:
def generate_start_end_doys(day_of_year, window):

    half_window = window // 2
    # check leap year
    is_leap_year = (day_of_year == 366)
    total_days = 366 if is_leap_year else 365
    
    start_day_of_year = (day_of_year - half_window) % total_days
    end_day_of_year = (day_of_year + half_window) % total_days
    
    return start_day_of_year, end_day_of_year

In [15]:
def compute_period_of_record_quantile(da, day_of_year, window, target_quantile):
    """
    Compute a single quantile value for IVT magnitude over rolling time window. In in this instance we subsetting the data for
    specific DOY periods - so we don't need to change the value of the window to account for the six-hour timesteps.
    Returned quantiles are for the entire period of record, so the values returned represent the q-th quantile
    for all observations within a time window (e.g. 5 months) centered on some DOY for all years in the record.
    This approach is closer to a "climatology" of q-th quantile IVT.
    """
    # check leap year
    leap_year = (day_of_year == 366)
    total_days = 366 if leap_year else 365
    
    # subset data for the specified day-of-year span
    start_day_of_year, end_day_of_year = generate_start_end_doys(day_of_year, window)
    
    if day_of_year >= window // 2 and 365 - day_of_year >= window // 2:
        # subset without wrapping around the year boundary (e.g., DOY is 180)
        subset = da.sel(time=((da.doy >= start_day_of_year) & (da.doy <= end_day_of_year)))
    else:
        # subset by wrapping around the year boundary (e.g., DOY is 360 and window is 30 days)
        subset = da.sel(time=((da.doy >= start_day_of_year) | (da.doy <= end_day_of_year)))

    if not leap_year:
        mask = subset['doy'] != 366
        subset = subset.where(mask, drop=True)


    result = subset.reduce(np.nanquantile, q=target_quantile, dim="time")
    return result
    

In [16]:
ds = xr.open_dataset(era5_fp)
# add DOY coords to input dataset
dsc = ds.assign_coords(doy=ds.time.dt.dayofyear)
dsc["ivt_mag"] = magnitude(dsc["p71.162"], dsc["p72.162"]).astype(int)
da = dsc["ivt_mag"]

quantile_results = []

for day_of_year in tqdm(range(1, 367)):
# keeping line below to test more rapidly, all DOYS takes ~7 minutes with no paralleization efforts
# for day_of_year in tqdm([1, 180, 366]):

    result = compute_period_of_record_quantile(da, day_of_year, window_days, quantile)
    
    quantile_results.append(result)

    
ds.close()


100%|███████████████████████████████████████████████████████████| 366/366 [06:11<00:00,  1.02s/it]


In [21]:
for i, da in enumerate(quantile_results):
    da = da.assign_coords(doy=i + 1)
    quantile_results[i] = da

# Concatenate the DataArrays along the 'doy' dimension
combined_da = xr.concat(quantile_results, dim='doy')

In [22]:
combined_da

<xarray.DataArray 'ivt_mag' (doy: 366, latitude: 41, longitude: 81)>
array([[[111.  , 114.75, 119.  , ...,  99.  , 100.  , 101.  ],
        [129.  , 134.  , 142.  , ..., 100.  , 101.  , 101.75],
        [152.75, 156.75, 157.  , ..., 102.  , 101.  , 102.  ],
        ...,
        [355.  , 354.75, 356.  , ..., 340.  , 337.  , 340.5 ],
        [358.  , 355.75, 358.5 , ..., 337.  , 333.75, 336.75],
        [365.  , 364.5 , 363.75, ..., 336.75, 335.5 , 334.  ]],

       [[111.  , 114.75, 119.  , ...,  99.  , 100.  , 101.  ],
        [128.  , 134.  , 142.  , ..., 100.  , 101.  , 102.  ],
        [151.75, 156.  , 155.75, ..., 102.  , 101.  , 102.  ],
        ...,
        [352.  , 352.75, 355.  , ..., 338.75, 334.75, 335.  ],
        [355.75, 353.75, 355.  , ..., 335.25, 331.75, 334.  ],
        [359.75, 361.  , 361.  , ..., 335.  , 333.  , 333.  ]],

       [[111.  , 115.  , 119.  , ...,  99.  , 100.  , 101.  ],
        [127.  , 133.  , 141.75, ..., 100.  , 100.  , 101.  ],
        [150.  , 155.  , 155.  , ..., 102.  , 101.  , 102.  ],
        ...,
...
        ...,
        [357.75, 359.  , 358.75, ..., 341.75, 343.5 , 342.75],
        [361.  , 362.5 , 365.  , ..., 340.  , 338.75, 341.  ],
        [368.75, 368.75, 366.75, ..., 338.  , 338.75, 339.5 ]],

       [[111.  , 114.  , 119.  , ...,  99.  , 100.  , 101.  ],
        [128.  , 133.75, 142.  , ..., 101.  , 101.  , 102.  ],
        [151.75, 156.  , 155.75, ..., 103.  , 101.75, 103.  ],
        ...,
        [357.  , 358.  , 358.  , ..., 341.  , 340.75, 342.  ],
        [360.  , 358.  , 362.75, ..., 340.  , 336.5 , 339.75],
        [366.75, 367.75, 365.  , ..., 338.  , 338.  , 337.  ]],

       [[110.55, 114.  , 119.  , ...,  99.  , 100.  , 101.  ],
        [128.  , 133.55, 142.  , ..., 100.  , 101.  , 101.55],
        [151.55, 156.  , 155.55, ..., 102.55, 101.  , 103.  ],
        ...,
        [356.55, 357.55, 357.1 , ..., 340.55, 339.  , 341.  ],
        [359.55, 357.55, 360.65, ..., 338.55, 334.  , 337.  ],
        [366.  , 366.55, 365.  , ..., 337.  , 336.  , 334.55]]])
Coordinates:
  * longitude  (longitude) float32 -150.0 -149.8 -149.5 ... -130.5 -130.2 -130.0
  * latitude   (latitude) float32 60.0 59.75 59.5 59.25 ... 50.5 50.25 50.0
  * doy        (doy) int64 1 2 3 4 5 6 7 8 9 ... 359 360 361 362 363 364 365 366

In [26]:
with xr.open_dataset(era5_fp) as ds:
    
    # add DOY coords to input dataset
    ds = ds.assign_coords(doy=ds.time.dt.dayofyear)

    # chunk to avoid memory error
    ds = ds.chunk({"latitude": 1, "longitude": 1})

    # p71.162 = code eastward "u" component
    # p72.162 = code for northward "v" component
    ds["ivt_mag"] = magnitude(ds["p71.162"], ds["p72.162"]).astype(int)
    ds["ivt_dir"] = direction(ds["p71.162"], ds["p72.162"]).astype(int)

    ds["ivt_seasonal_quantile"] = ds["ivt_mag"].map_blocks(compute_seasonal_quantile, kwargs={"window": window_days, "target_quantile" : quantile},
                                                           template=ds["ivt_mag"]).compute()
    
    ds["ivt_por_normal_quantile"] = combined_da
    
    #ds["ivt_por_quantile"] = ds["ivt_mag"].map_blocks(normal_pctile, kwargs={"window": ar_params['window'], "percentile" : q}, template=ds["ivt_mag"]).compute()

    # ds.to_netcdf(ard_fp)
ds

<xarray.Dataset>
Dimensions:                  (longitude: 81, latitude: 41, time: 5844, doy: 366)
Coordinates:
  * longitude                (longitude) float32 -150.0 -149.8 ... -130.2 -130.0
  * latitude                 (latitude) float32 60.0 59.75 59.5 ... 50.25 50.0
  * time                     (time) datetime64[ns] 2019-01-01 ... 2022-12-31T...
  * doy                      (doy) int64 1 2 3 4 5 6 ... 361 362 363 364 365 366
Data variables:
    p71.162                  (time, latitude, longitude) float32 dask.array<chunksize=(5844, 1, 1), meta=np.ndarray>
    p72.162                  (time, latitude, longitude) float32 dask.array<chunksize=(5844, 1, 1), meta=np.ndarray>
    ivt_mag                  (time, latitude, longitude) int64 dask.array<chunksize=(5844, 1, 1), meta=np.ndarray>
    ivt_dir                  (time, latitude, longitude) int64 dask.array<chunksize=(5844, 1, 1), meta=np.ndarray>
    ivt_seasonal_quantile    (time, latitude, longitude) float64 nan nan ... nan
    ivt_por_normal_quantile  (doy, latitude, longitude) float64 111.0 ... 334.5
Attributes:
    Conventions:  CF-1.6
    history:      2023-06-12 18:18:10 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [27]:
client.close()

In [28]:
ds.to_netcdf(ard_fp)
